apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    name: hyperscale-tls
  name: hyperscale-tls
  namespace: hyperscale-services
spec:
  dnsNames:
  - hyperscale.k8s.delphixdemo.com
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: hyperscale-tls
