apiVersion: v1
kind: PersistentVolume
metadata:
  name: stage-storage-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
 # persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /domain0/group-2/appdata_container-812/appdata_timeflow-813/datafile
    server: 10.0.1.30
    readOnly: false
