apiVersion: v1
kind: Service
metadata:
  labels:
    io.hyperscale.service: controller-service
  name: controller-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: "tcp"
      port: 8080
      targetPort: 8080
  selector:
    io.hyperscale.service: controller-service
status:
  loadBalancer: {}
