#
# Copyright (c) 2024 by Delphix. All rights reserved.
#

  {{- if (not .Values.unload.dbPvcName) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.hyperscale.service: unload-database-pvc
  name: unload-database-pvc
  namespace: {{ .Values.namespace }}
spec:
  {{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.unload.databaseStorageSize }}
status: {}
  {{- end }}
